// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: drawer/v1/drawer.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Drawer_GetZenPic_FullMethodName = "/drawer.v1.Drawer/GetZenPic"
)

// DrawerClient is the client API for Drawer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DrawerClient interface {
	GetZenPic(ctx context.Context, in *ZenRequest, opts ...grpc.CallOption) (*PictureReply, error)
}

type drawerClient struct {
	cc grpc.ClientConnInterface
}

func NewDrawerClient(cc grpc.ClientConnInterface) DrawerClient {
	return &drawerClient{cc}
}

func (c *drawerClient) GetZenPic(ctx context.Context, in *ZenRequest, opts ...grpc.CallOption) (*PictureReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PictureReply)
	err := c.cc.Invoke(ctx, Drawer_GetZenPic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrawerServer is the server API for Drawer service.
// All implementations must embed UnimplementedDrawerServer
// for forward compatibility.
type DrawerServer interface {
	GetZenPic(context.Context, *ZenRequest) (*PictureReply, error)
	mustEmbedUnimplementedDrawerServer()
}

// UnimplementedDrawerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDrawerServer struct{}

func (UnimplementedDrawerServer) GetZenPic(context.Context, *ZenRequest) (*PictureReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetZenPic not implemented")
}
func (UnimplementedDrawerServer) mustEmbedUnimplementedDrawerServer() {}
func (UnimplementedDrawerServer) testEmbeddedByValue()                {}

// UnsafeDrawerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DrawerServer will
// result in compilation errors.
type UnsafeDrawerServer interface {
	mustEmbedUnimplementedDrawerServer()
}

func RegisterDrawerServer(s grpc.ServiceRegistrar, srv DrawerServer) {
	// If the following call pancis, it indicates UnimplementedDrawerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Drawer_ServiceDesc, srv)
}

func _Drawer_GetZenPic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrawerServer).GetZenPic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drawer_GetZenPic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrawerServer).GetZenPic(ctx, req.(*ZenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Drawer_ServiceDesc is the grpc.ServiceDesc for Drawer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Drawer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drawer.v1.Drawer",
	HandlerType: (*DrawerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetZenPic",
			Handler:    _Drawer_GetZenPic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drawer/v1/drawer.proto",
}
