// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: datahub/v1/datahub.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Datahub_GetSymbols_FullMethodName = "/datahub.v1.Datahub/GetSymbols"
	Datahub_GetKline_FullMethodName   = "/datahub.v1.Datahub/GetKline"
	Datahub_GetSymbol_FullMethodName  = "/datahub.v1.Datahub/GetSymbol"
)

// DatahubClient is the client API for Datahub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatahubClient interface {
	// 获取所有交易对
	GetSymbols(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SymbolsReply, error)
	// 获取指定交易对的K线数据
	GetKline(ctx context.Context, in *KlineRequest, opts ...grpc.CallOption) (*KlineReply, error)
	// 获取指定交易对的信息
	GetSymbol(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (*SymbolReply, error)
}

type datahubClient struct {
	cc grpc.ClientConnInterface
}

func NewDatahubClient(cc grpc.ClientConnInterface) DatahubClient {
	return &datahubClient{cc}
}

func (c *datahubClient) GetSymbols(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SymbolsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymbolsReply)
	err := c.cc.Invoke(ctx, Datahub_GetSymbols_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubClient) GetKline(ctx context.Context, in *KlineRequest, opts ...grpc.CallOption) (*KlineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KlineReply)
	err := c.cc.Invoke(ctx, Datahub_GetKline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *datahubClient) GetSymbol(ctx context.Context, in *SymbolRequest, opts ...grpc.CallOption) (*SymbolReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SymbolReply)
	err := c.cc.Invoke(ctx, Datahub_GetSymbol_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatahubServer is the server API for Datahub service.
// All implementations must embed UnimplementedDatahubServer
// for forward compatibility.
type DatahubServer interface {
	// 获取所有交易对
	GetSymbols(context.Context, *emptypb.Empty) (*SymbolsReply, error)
	// 获取指定交易对的K线数据
	GetKline(context.Context, *KlineRequest) (*KlineReply, error)
	// 获取指定交易对的信息
	GetSymbol(context.Context, *SymbolRequest) (*SymbolReply, error)
	mustEmbedUnimplementedDatahubServer()
}

// UnimplementedDatahubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatahubServer struct{}

func (UnimplementedDatahubServer) GetSymbols(context.Context, *emptypb.Empty) (*SymbolsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbols not implemented")
}
func (UnimplementedDatahubServer) GetKline(context.Context, *KlineRequest) (*KlineReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKline not implemented")
}
func (UnimplementedDatahubServer) GetSymbol(context.Context, *SymbolRequest) (*SymbolReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSymbol not implemented")
}
func (UnimplementedDatahubServer) mustEmbedUnimplementedDatahubServer() {}
func (UnimplementedDatahubServer) testEmbeddedByValue()                 {}

// UnsafeDatahubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatahubServer will
// result in compilation errors.
type UnsafeDatahubServer interface {
	mustEmbedUnimplementedDatahubServer()
}

func RegisterDatahubServer(s grpc.ServiceRegistrar, srv DatahubServer) {
	// If the following call pancis, it indicates UnimplementedDatahubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Datahub_ServiceDesc, srv)
}

func _Datahub_GetSymbols_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServer).GetSymbols(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datahub_GetSymbols_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServer).GetSymbols(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datahub_GetKline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServer).GetKline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datahub_GetKline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServer).GetKline(ctx, req.(*KlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Datahub_GetSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatahubServer).GetSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Datahub_GetSymbol_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatahubServer).GetSymbol(ctx, req.(*SymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Datahub_ServiceDesc is the grpc.ServiceDesc for Datahub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Datahub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "datahub.v1.Datahub",
	HandlerType: (*DatahubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSymbols",
			Handler:    _Datahub_GetSymbols_Handler,
		},
		{
			MethodName: "GetKline",
			Handler:    _Datahub_GetKline_Handler,
		},
		{
			MethodName: "GetSymbol",
			Handler:    _Datahub_GetSymbol_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datahub/v1/datahub.proto",
}
